<a href="https://colab.research.google.com/github/asrinvakili/PythonLibraries/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installation of Pandas:

*            pip install pandas

## Import Pandas:

In [1]:
import pandas as pd

In [4]:
a1 = [1, 2, 3, 4, 5]

pd1 = pd.Series(a1)

pd1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
a2 = [1, 2, 3, 4, 5]

b2 = ['a', 'b', 'c', 'd', 'e']

pd2 = pd.Series(b2, index = a2)

pd2

1    a
2    b
3    c
4    d
5    e
dtype: object

In [6]:
a3 = {"BMW": 18000, "Volvo": 70000, "Ford": 20000}

pd3 = pd.Series(a3)

pd3

BMW      18000
Volvo    70000
Ford     20000
dtype: int64

In [10]:
data1 = {
  'cars': ["BMW", "Volvo", "Ford"],
  'price': [18000, 70000, 20000]
}

df1 = pd.DataFrame(data1)

df1

    cars  price
0    BMW  18000
1  Volvo  70000
2   Ford  20000

In [8]:
#refer to the row index:

df1.loc[1]

cars     Volvo
price    70000
Name: 1, dtype: object

In [9]:
#use a list of indexes:

df1.loc[[0, 1]]

    cars  price
0    BMW  18000
1  Volvo  70000

In [11]:
data2 = {
  'cars': ["BMW", "Volvo", "Ford"],
  'price': [18000, 70000, 20000]
}

df2 = pd.DataFrame(data2, index = ['car1', 'car2', 'car3'])

df2.loc['car3']

cars      Ford
price    20000
Name: car3, dtype: object

## Import Data From CSV

In [ ]:
df3 = pd.read_csv('data.csv')

df3.to_string()

In [ ]:
#Increase the maximum number of rows to display the entire DataFrame:

pd.options.display.max_rows = 9999

df4 = pd.read_csv('data.csv')

df4

In [ ]:
df5 = pd.read_csv('data.csv')

#show headers and a specified number of rows.
#if head() show only 5 rows
df5.head(10)

In [ ]:
#show last 5 rows

df5.tail()

In [ ]:
#show information about number of columns/rows, type of data etc.

df5.info()

# **Data Cleaning**